spring.application.name=SpringTrazabilidades

#BBDD
spring.datasource.url=jdbc:mariadb://localhost:3309/spring_trazabilidades
spring.datasource.username=usuario
spring.datasource.password=usuario1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#none, create
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#JWT
jwt.secret=bxq30qgYzk9ipXZqB9z6uMyxipIn1PTkFtx2WcP5MKQ=
#jwt.expiration=3600000

#CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://184.73.39.231:5173,http://184.73.39.231:3000
